#include "motor.h"
#include "tim.h"

void MotorA_Control(uint16_t speed, MotorDir_t direction)
{

	__HAL_TIM_SET_COMPARE(&htim10,TIM_CHANNEL_1,speed);

	switch(direction){
	case DIR_STOP:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_FORWARD_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_BACKWARD_PIN, GPIO_PIN_RESET);
		break;
	case DIR_FORWARD:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_FORWARD_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_BACKWARD_PIN, GPIO_PIN_RESET);
		break;
	case DIR_BACKWARD:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_FORWARD_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_A_BACKWARD_PIN, GPIO_PIN_SET);
		break;
	}
}

void MotorB_Control(uint16_t speed, MotorDir_t direction)
{

	__HAL_TIM_SET_COMPARE(&htim11,TIM_CHANNEL_1,speed);

	switch(direction){
	case DIR_STOP:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_FORWARD_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_BACKWARD_PIN, GPIO_PIN_RESET);
		break;
	case DIR_FORWARD:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_FORWARD_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_BACKWARD_PIN, GPIO_PIN_RESET);
		break;
	case DIR_BACKWARD:
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_FORWARD_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(MOTOR_GPIO_PORT, MOTOR_B_BACKWARD_PIN, GPIO_PIN_SET);
		break;
	}
}
